name: 'ecommerce_analytics'
version: '1.0'
config-version: 2
profile: 'ecommerce_analytics'

model-paths: ["models"]
target-path: "target" 
clean-targets: ["target"]

models:
  ecommerce_analytics:
    +materialized: table
